# Project information
site_name: Core-Geth Documentation
site_description: Documentation for Core-Geth Ethereum Protocol Provider
site_url: https://docs.coregeth.com/
site_author: Core-Geth Team

# Repository
repo_name: ethereumclassic/core-geth
repo_url: https://github.com/ethereumclassic/core-geth
edit_uri: edit/master/docs/

# Copyright
copyright: 'Copyright &copy; The go-ethereum Authors, The multi-geth Authors and The core-geth Authors. Licensed under the GNU GPL v3 and LGPL v3; see the <a href="https://github.com/ethereumclassic/core-geth/blob/master/COPYING">COPYING</a> and <a href="https://github.com/ethereumclassic/core-geth/blob/master/COPYING.LESSER">COPYING.LESSER</a> files.'

# Configuration
theme:
  # https://github.com/squidfunk/mkdocs-material/tree/master/src
  name: material
  logo: img/favicon.png
  favicon: img/favicon.png
  language: en

  palette:
    scheme: slate
    primary: black
    accent: green

  icon:
    repo: fontawesome/brands/github

  # Don't include MkDocs' JavaScript
  include_search_page: false

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    # - navigation.instant
    - navigation.tracking
    - navigation.top

extra_css:
  - assets/css/extra.css

use_directory_urls: true

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  # - meta
  - smarty
  - toc:
      permalink: true
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      linenums: true
